project:
  name: Pizza Sales Analysis
  description: >
    A complete sales analysis project using SQL and Power BI to explore
    pizza sales data for trends, product performance, and peak business hours.
  tools:
    - MySQL Workbench 8.0 CE
    - Power BI
  dataset:
    source: Kaggle
    rows: 49600
    cleaned: true
    transformations:
      - Date formatting
      - Duplicate removal
      - Sorting and filtering
      - New columns: day name/number, month name/number
  insights:
    total_orders: 21350
    total_pizzas_sold: 49574
    total_revenue: 817860
    avg_order_value: 38.31
    avg_pizzas_per_order: 2.32
    peak_days: ["Friday", "Saturday"]
    peak_months: ["July", "January"]
    top_pizza_by_revenue: "Thai Chicken"
    top_by_quantity_sold: "Classic Deluxe"
    top_category: "Classic"
    top_size: "Large"
  files:
    - SQL/pizza_sales_queries.sql
    - PowerBI/pizza_sales_dashboard.pbix
    - README.md
    - config.yaml
    - assets/dashboard_screenshots.png
